# config/token.yaml
# token:

# config/database.yaml
# database:
#   bal:  # semantic database key
#     host:
#     port:
#     service_name:  # sid
#     user:
#     password:
#   kor:  # another semantic database key
#     host:
#     port:
#     service_name:
#     user:
#     password:

# config/config.yaml
webapp:
  host: 0.0.0.0
  port: 5001

sqlite:
  database: /var/lib/sqlite/tsheesrv.db
  echo: False

oracle:
  nls_lang: RUSSIAN_RUSSIA.CL8MSWIN1251
  min_pool: 0  # минимальное число соединений в пуле на каждую базу данных
  max_pool: 4  # максимальное число соединений в пуле на каждую базу данных

developer:
  name: Павел Александрович Никитин
  telegram: '@nikitinpa'

use_log_file: False
log_file: /var/log/tsheebot.log

use_pid_file: False
pid_file: /var/run/tsheebot.pid
