# config/token.yaml
# token:

# config/database.yaml
# database:
#   bal:  # semantic database key
#     host:
#     port:
#     service_name:  # sid
#     user:
#     password:
#   kor:  # another semantic database key
#     host:
#     port:
#     service_name:
#     user:
#     password:

# config/config.yaml
webapp:
  host: 0.0.0.0
  port: 5001

webhook:
  url: https://api.parusinf.ru
  cert_path: cert/api-parusinf-ru.crt

sqlite:
  database: tsheesrv.db
  echo: False

oracle:
  nls_lang: RUSSIAN_RUSSIA.CL8MSWIN1251
  min_pool: 1  # минимальное число соединений в пуле на одну базу
  max_pool: 4  # максимальное число соединений в пуле на одну базу

developer:
  name: Павел Никитин
  telegram: '@nikitinpa'
